export { default as Header } from "./Header";
export { default as Footer } from "./Footer";
export { default as Banner } from "./home/Banner";
export { default as TrustedSection } from "./home/TrustedSection";
export { default as TowsSection } from "./home/TowsSection";
export { default as OurProject } from "./home/OurProject";
export { default as MeetOurTeam } from "./home/MeetOurTeam";
export { default as Contact } from "./home/Contact";
export { default as ContactUs } from "./home/ContactUs";